# Generated by Django 5.0.1 on 2024-01-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id_dice', models.AutoField(primary_key=True, serialize=False)),
                ('sides', models.IntegerField()),
            ],
        ),
    ]
